[pytest]
addopts = -v --alluredir=allure-results --clean-alluredir
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    ui: UI test (Playwright browser)
    api: API test (Playwright APIRequestContext)
    combined: Test kết hợp cả UI và API
    profile: Nhóm chức năng Change my profile
    settings: Nhóm chức năng Setting account
    smoke: Test smoke / must-pass

log_cli = true
log_cli_level = INFO
